import type { Metadata } from "next";
import { Montserrat, JetBrains_Mono, Abril_Fatface } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsmono",
  subsets: ["latin"],
});

const abrilFatface = Abril_Fatface({
  variable: "--font-abrilfatface",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Evan Alvarez",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${jetbrainsMono.variable} ${abrilFatface.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
